# ----------------
# nvim
# tag: nvim.sdk
# base: debian:bullseye
# docs: https://github.com/sar/nvim-docker
# ----------------

version: "3.3"

services:
  nvim:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - HOST_GID=${HOST_GID}
        - DEFAULT_USER=${DEFAULT_USER}
        - SUDO_PASSWORD=${SUDO_PASSWORD}
    image: nvim.sdk
    container_name: nvim.runtime
    privileged: false
    user: "${UID}:${GID}"
    env_file: .env
    ports:
      - "5000-5010:5000-5010"
      - "8000-8010:8000-8010"
    networks:
      - nvim
    volumes:
      - ${HOST_CODE_PATH}:${CODE_PATH}:z
      - ${HOST_NVIM_PATH}:/home/${DEFAULT_USER}/.config/nvim
      - ${HOST_NVIM_PATH}/gh:/home/${DEFAULT_USER}/.config/gh
      - nvim_cache:/home/${DEFAULT_USER}/.local/share/nvim
      - nvim_logs:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
    tmpfs:
      - /home/${DEFAULT_USER}/.local/share/NuGet
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 60s

volumes:
  nvim_cache:
  nvim_logs:

networks:
  nvim:
    driver: bridge
